// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // DATABASE_URL is read from environment variables.
    //
    // Local development: .env file
    // CI testing: hardcoded local PostgreSQL
    // Production migrations: GitHub secret PRODUCTION_DATABASE_URL
    // Production runtime: Vercel environment variable
    url: process.env["DATABASE_URL"],
    directUrl: process.env["DIRECT_DATABASE_URL"],
  },
});
