apiVersion: apps/v1
kind: Deployment
metadata:
  name: vrs-app
  namespace: vrs-app
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
        - name: run-migrations
          image: ghcr.io/aungkyephyo2215/vct-visitor-registration-system:staging
        - name: seed-database
          image: ghcr.io/aungkyephyo2215/vct-visitor-registration-system:staging
      containers:
        - name: vrs-app
          # GitHub Actions builds this image on every push to staging/argocd-k8s-lab
          # Tag format: staging (from branch name)
          image: ghcr.io/aungkyephyo2215/vct-visitor-registration-system:staging
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
