apiVersion: apps/v1
kind: Deployment
metadata:
  name: vrs-app
  namespace: vrs-app
spec:
  selector:
    matchLabels:
      app: vrs-app
  template:
    spec:
      containers:
        - name: vrs-app
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 384Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vrs-postgres
  namespace: vrs-postgres
spec:
  selector:
    matchLabels:
      app: vrs-postgres
  serviceName: vrs-postgres
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
