apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vrs-postgres-data
  namespace: vrs-postgres
  labels:
    app.kubernetes.io/name: vrs-postgres
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # K3s uses local-path-provisioner by default
  # storageClassName: local-path
