apiVersion: v1
kind: ResourceQuota
metadata:
  name: vrs-postgres-quota
  namespace: vrs-postgres
  labels:
    app.kubernetes.io/name: vrs-postgres
    app.kubernetes.io/component: database
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "3"
