apiVersion: v1
kind: Service
metadata:
  name: vrs-postgres
  namespace: vrs-postgres
  labels:
    app.kubernetes.io/name: vrs-postgres
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vrs-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
