apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: visitor-registration-system
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: visitor-registration-system
    environment: staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # TODO: Update repoURL to your actual Git repository
    repoURL: https://github.com/aungyephyo2215/vct-visitor-registration-system.git
    targetRevision: staging/argocd-k8s-lab
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: vrs-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  # Ignore known cosmetic differences
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.volumeClaimTemplates[] | .spec.resources.requests.storage
      jsonPointers:
        - /metadata/managedFields
        - /spec/updateStrategy/rollingUpdate
        - /spec/podManagementPolicy
  info:
    - name: environment
      value: staging
    - name: team
      value: visitor-registration
